version: "3.9"
services:
  backend:
    build:
      context: .
      target: development # or production
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
      - /tmp:/var/lib/postgresql/data
      - postgres:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /var/lib/postgresql/data/pgdata
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass qwerasdf
    environment:
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL,CONFIG
    volumes: 
      - redis:/data

volumes:
  postgres:
  redis:
