apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortner
  template:
    metadata:
      labels:
        app: url-shortner
    spec:
      containers:
        - name: url-shortner
          image: url-shortner:v0.0.3
          imagePullPolicy: Never  # Use only the locally built image
          ports:
            - containerPort: 8000
